REM   Script: Session 01
REM   session 01

CREATE TABLE STATION  
(ID INT PRIMARY KEY, 
    CITY CHAR(20), 
    STATE CHAR(2), 
    LAT_N REAL, 
    LONG_W REAL);

INSERT INTO STATION VALUES (13,'PHOENIX','AZ',33,112);

INSERT INTO STATION VALUES (44,'DENVER','CO',40,105);

INSERT INTO STATION VALUES (66,'CARIBOU','ME',47,68);

SELECT* FROM STATION  
;

SELECT* FROM STATION 
WHERE LAT_N > 39.7;

CREATE TABLE STATS 
(ID INT REFERENCES STATION (ID), 
    MONTH INT CHECK (MONTH BETWEEN 1 AND 12), 
    TEMP_F REAL CHECK (TEMP_F BETWEEN -80 AND 150), 
    RAIN_I REAL CHECK (RAIN_I BETWEEN 0 AND 100), 
    PRIMARY KEY (ID,MONTH));

INSERT INTO STATS VALUES (13, 1, 57.4, 0.31);

INSERT INTO STATS VALUES (13, 7, 91.7, 5.15);

INSERT INTO STATS VALUES (44, 1, 27.3, 0.18);

INSERT INTO STATS VALUES (44, 7, 74.8, 2.11);

INSERT INTO STATS VALUES (66, 1, 6.7, 2.10);

INSERT INTO STATS VALUES (66, 7, 65.8, 4.52);

SELECT CITY, TEMP_F FROM STATION 
    INNER JOIN STATS 
    ON STATS.ID = STATION.ID 
    ORDER BY CITY;

CREATE VIEW METRIC_STATS ( CITY, MONTH, TEMP_C, RAIN_C) AS  
    SELECT CITY, 
    MONTH, 
    (TEMP_F -32)* 5/9 , 
    RAIN_I * 2.54 
    FROM STATS 
       INNER JOIN STATION  
    ON STATS.ID = STATION.ID 
;

SELECT * FROM METRIC_STATS;

